config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :journals do
    collection do
      get '/user_journals', to: 'journals#user_journals', as: :user
    end
  end
  resources :posts
  resources :users
  resources :groups do |t|
    member do
      post :create_role
    end
    member do
      delete :delete_role
    end
    member do
      post :add_track, path: '/add_track'
    end
    member do
      delete :delete_track
    end
    resources :posts do
      collection do
        get '/user_posts', to: 'posts#user_posts', as: :user
      end
    end
    resources :tracks do
      resources :activities do
        member do
          get :receive
        end
        member do
          get :reflect
        end
        member do
          get :respond
        end
      end
    end
  end
  
  resources :tracks do |t|
  	member do
      post :create_selection
    end
    resources :activities do
      member do
        get :receive
      end
      member do
        get :reflect
      end
      member do
        get :respond
      end
    end
  end
  resources :scriptures
  resources :roles
  resources :selections
  resources :organizations do
    resources :groups do
    end
  end
  #root 'posts#user_posts'
  root 'journals#user_journals'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :track
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :roles
  has_many :users, through: :roles
  has_many :posts
  has_many :selections
  has_many :tracks, through: :selections
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :group
  belongs_to :user

  enum role_type: {
    teacher: 1,
    student: 2
  }

  validates :group, presence: true
  validates :user,  presence: true

end

app/models/scripture.rb
class Scripture < ApplicationRecord
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :group
  belongs_to :track
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :activities, dependent: :destroy
  accepts_nested_attributes_for :activities
  has_many :selections
  has_many :groups, through: :selections
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  has_many :roles
  has_many :groups, through: :roles
  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :posts
  has_many :journals
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    #@groups = Group.find(params[:id])
    @group = Group.find(params[:group_id])
    @posts = @group.posts.order(id: :desc)
    @tracks = @group.tracks.all  
    @user = current_user
  
    respond_to do |format|
      format.html
      format.xml { render :xml => @posts}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    group = Group.find(params[:group_id])
    @post = group.posts

    respond_to do |format|
      format.html
      format.xml { render :xml => @post }
    end
  end

  # GET /posts/new
  def new
    @group = Group.find(params[:group_id])
    @post = @group.posts.build
    @user = current_user

    respond_to do |format|
      format.html
      format.xml { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
   @group = Group.find(params[:group_id])
   @post = @group.posts.find(params[:id])
   # @post = Post.find(params[:id])
    @user = current_user
  end

  # POST /posts
  # POST /posts.json
  def create
    @group = Group.find(params[:group_id])
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id
    @groups = Group.all

    respond_to do |format|
      if @post.save
        format.html { redirect_to group_posts_path(@group), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @group = Group.find(params[:group_id])
    #@post = post.find(params[:id])
    @post = @group.posts.find(params[:id])
    @user = current_user

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to group_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    group = Group.find(params[:group_id])
    @post = group.posts.find(params[:id])
    #@post = posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to group_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_posts
    @posts = policy_scope(Post).order(id: :desc)
    @tracks = Track.all
    @user = current_user
    @groups = Group.all

  end


  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:published, :content, :user_id, :group_id, user_attributes: [:name], group_attributes: [:title])
    end

  end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track

  
  def index
    @tracks = Track.all
    @user = current_user
  end

  def show
    @track = Track.find(params[:id])

  end

  def new
    @track = Track.new
    authorize @track
    
  end

  def edit
    @track= Track.find(params[:id])
  end

  def create
    @track = Track.new(track_params)
 
    if @track.save
      redirect_to @track
    else
    	render 'new'
    end
  end

  def update
  	@track = Track.find(params[:id])

  	if @track.update(track_params)
  		redirect_to @track
  	else
  		render 'edit'
  	end
  end
  
  def create_selection
    group_id = selection_params[:group_id]
    track_id = @track.track_id
    selection = Selection.new(group_id: group_id, track_id: track_id)

    if selection.save!
      redirect to group_posts_path(@group)
    else
      redirect to tracks_path
    end
  end

  def destroy
  	@track = Track.find(params[:id])
  	@track.destroy

  	redirect_to tracks_path
  end

  private

  def set_track
    @track = Track.find_by(id: params[:id])
  end
  
  def group_params
    params.require(:group).permit(:title)
  end

  def selection_params
    params.require(:selection).permit(:group_id, :track_id)
  end
  
  def track_params
    params.require(:track).permit(:track_id, :title, :description, :activities_attributes => [:title, :receive, :reflect, :respond])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tracks/_form.html.erb
<%= form_for @track do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@track.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @track.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div>
    <%= f.submit class: "btn btn-primary"%>
  </div>

  <% end %>

app/views/tracks/edit.html.erb
<div class="container-fluid">
<h1>Edit Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>
</div>

app/views/tracks/index.html.erb
<p>
<div class="container">
<div class="card card-block">
  <h1 class="card-title">Tracks</h1>
  <p class="card-text">
        <% if current_user.admin? %>
        <%= button_to 'Create a Track', new_track_path, method: :get, class: "btn btn-primary" %>
        <% end %>
 <p>
<div class="container">
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
   
   <tbody>
     <% @tracks.each do |track| %>
      <td><%= track.title %></td>
      <td><%= track.description %></td>
      <td><%= link_to 'View Activities', track_path(track) %></td>
      <% if current_user.admin? %>
      <td><%= link_to 'Edit', edit_track_path(track) %></td>
      <td><%= link_to 'Destroy', track_path(track),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>  
      <% end %>
      <td></td>
      <td></td>
    </tr>
  <% end %>
  </tbody>
</table>

</div>
</p>
</div>
</div>

app/views/tracks/new.html.erb
<div class="container">
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>
<div>

app/views/tracks/show.html.erb
<p>
<div class="container">
<div class="card card-block">
  <h1 class="card-title"><%= @track.title %></h1>
  <p class="card-text">
    
  <p><%= @track.description %></p>
   
<p>
<div class="container">

<table class="table table-striped">
  <thead>
    <th><h4>Activities</h4></th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

  <% @track.activities.each do |activity| %>
   <tr>
    <td><%= activity.title %></td>
    <td><%= link_to 'Begin', receive_track_activity_path(activity.track, activity) %></td>
    <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_track_activity_path(activity.track, activity) %></td>
    <td><%= link_to 'Destroy',track_activity_path(activity.track, activity), method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<p>
<div class="action">
<% if current_user.admin? %>
<%= link_to 'New Activity', new_track_activity_path(@track) %>  |<% end %>
<%= link_to 'Back to Tracks', tracks_path %>
</div>
</p>
</div>
</div>