config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :journals do
    collection do
      get '/user_journals', to: 'journals#user_journals', as: :user
    end
  end
  resources :posts
  resources :users
  resources :groups do |t|
    member do
      post :create_role
    end
    member do
      delete :delete_role
    end
    member do
      post :add_track, path: '/add_track'
    end
    member do
      delete :delete_track
    end
    resources :posts do
      collection do
        get '/user_posts', to: 'posts#user_posts', as: :user
      end
    end
    resources :tracks do
      resources :activities do
        member do
          get :receive
        end
        member do
          get :reflect
        end
        member do
          get :respond
        end
      end
    end
  end
  
  resources :tracks do |t|
  	member do
      post :create_selection
    end
    resources :activities do
      member do
        get :receive
      end
      member do
        get :reflect
      end
      member do
        get :respond
      end
    end
  end
  resources :scriptures
  resources :roles
  resources :selections
  resources :organizations do
    resources :groups do
    end
  end
  #root 'posts#user_posts'
  root 'journals#user_journals'
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  
  
  # GET /journals
  # GET /journals.json
  def index
    @user = current_user
    @journals = Journal.all
    #@user = User.find(params[:id])
    #@journals = @user.journals.all
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    @user = current_user
    @journal = Journal.find(params[:id])
  end

  # GET /journals/new
  def new
    @user = current_user
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
    @user = current_user
    @journal = Journal.find(params[:id])
  end

  # POST /journals
  # POST /journals.json
  def create
    #@user = current_user
    @journal = Journal.new(journal_params)
    @journal.user_id = current_user.id
    

    respond_to do |format|
      if @journal.save
        format.html { redirect_to root_path, notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    #raise params.inspect
    @user = current_user
    @journal = Journal.find(params[:id])
    
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to root_path, notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @user = current_user
    @journal = Journal.find(params[:id])
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_journals
    @journals = policy_scope(Journal).order(id: :desc)
    #@tracks = Track.all
    @user = current_user
    #@groups = Group.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:entry, :user_id)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for (journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :entry %>
    <%= f.text_area :entry, :rows => "7", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/journals/_journal.html.erb
<div class="card card-block" >
  <div class="card-header">
    <%= @user.name %><br />
  </div>
  <div class="card-block">
    <!--<%# @journals.each do |journal| %>-->
      <p class="card-text"><%= journal.entry %></p>
     
  </div>
  <div class="card-footer">
    <%#=entry.journal.published.strftime("%B %e, %Y %I %p") %><br />
    <%# if policy(post).edit? %>
    <%#= link_to 'Edit', edit_group_post_path(post.group, post) %>
    <%# end %>
    <% #if policy(post).destroy? %> 
    <%#= link_to 'Delete', group_post_path(post.group, post), method: :delete, data: { confirm: 'Are you sure?'} %>
    <%# end %>
  </div>
</div>

app/views/journals/_list.html.erb
<%= render 'journal' %>

app/views/journals/edit.html.erb
<div class="container-fluid">
<h1>Edit Journal</h1><br>

<%= render 'form', journal: @journal %>

<br>
<%= link_to 'Back', journals_path %>
</div>

app/views/journals/index.html.erb
<div class="container-fluid">
  <p>
<div class="row-fluid">
  <div class="col-sm-7">
    <div class="card card-block">
    <h4 class="card-title">Journal Entries</h4>
    
        <%= link_to 'New Journal Entry', new_journal_path %>
        <%= link_to 'User Journals', user_journals_path %>
<p>
        <table>
         <thead>
          <tr>
           <th colspan="3"></th>
            </tr>
          </thead>

         <tbody>
          <% @journals.each do |journal| %> 
           <tr>
             <td><%= journal.entry %></td>
             <td><%#= user_id.name(journal) %>
             <td><%= link_to 'Show', journal_path(journal) %>  |</td>  
             <td><%= link_to 'Edit', edit_journal_path(journal) %>  |</td> 
            <td><%= link_to 'Destroy', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
         <% end %>
        </tbody>
       </table>
         
    </div>
  </div>


<div class="col-sm-4">
  <div class="card card-block">
    <h4 class="card-title">You are on your personal page.</h4>
      <p>New entries will be kept private unless marked public.</p>
        
  </div>

   <div class="card card-block">
      <h4 class="card-title">My Groups</h4>
     <div class="container-fluid">
       <% @user.groups.each do |group| %>
         <a href="<%= group_posts_path(group) %>" class="list-group-item list-group-item-action"><%= group.title %></a><br />
      <% end %>
     </div>     
   </div>

</div>

app/views/journals/new.html.erb
<div class="container-fluid">
<h1>New Journal</h1>

<%= render 'form', journal: @journal %>
<br>
<%= link_to 'Back', root_path %>
</div>

app/views/journals/show.html.erb
<div class="container-fluid">
<h1>My Journal Entry</h1>

<h3><%= @journal.entry %></h3>


<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', root_path %>
</div>

app/views/journals/user_journals.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title"><%= @user.name %>'s Journal Entries</h4>
          <!--<a href="<%= new_journal_path %>" class="card-link">New Journal Entry</a>-->
        </div>
      </div>
      <div class="card">
        <div class="card-block">    
          <div class="container">
            <%= form_for :journal, url: journals_path do |f| %>
              <p>
              <div class="form-group">
                <%= f.label :new_journal_entry %><br>
                <%= f.text_area :entry, :rows => "3", class: "form-control" %>
              </div>
              <div class="actions">
                <%= f.submit "Save Entry"  %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% @journals.each do |journal| %>
       <div class="card">
         <div class="card-block">
           <h4 class="card-header"><%= journal.created_at.strftime("%B %e, %Y") %></h4>
           <div class="card-block">
             <p class="card-text"><%= journal.entry %></p>
           </div>
           <div class="card-footer">
             <a href="<%= edit_journal_path(journal) %>" class="card-link">Edit</a>  |
             <%= link_to 'Delete', journal_path(journal), method: :delete, data: { confirm: 'Are you sure?' } %> |
             <a href="#" class="card-link">Share with Group</a>
           </div>
         </div>
       </div>
      <% end %>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">You are on your personal page.</h4>
          <p>New posts will be kept private unless shared with a group.</p>
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Switch Groups</a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <% @user.groups.each do |group| %>
              <a class="dropdown-item" href="<%= group_posts_path(group) %>">Go to <%= group.title %></a>
              <% end %> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


 <!--nd %>
            </div>
      </div>-->