config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :journals do
    collection do
      get '/user_journals', to: 'journals#user_journals', as: :user
    end
  end
  resources :posts
  resources :users
  resources :groups do |t|
    member do
      post :create_role
    end
    member do
      delete :delete_role
    end
    member do
      post :add_track, path: '/add_track'
    end
    member do
      delete :delete_track
    end
    resources :posts do
      collection do
        get '/user_posts', to: 'posts#user_posts', as: :user
      end
    end
    resources :tracks do
      resources :activities do
        member do
          get :receive
        end
        member do
          get :reflect
        end
        member do
          get :respond
        end
      end
    end
  end
  
  resources :tracks do |t|
  	member do
      post :create_selection
    end
    resources :activities do
      member do
        get :receive
      end
      member do
        get :reflect
      end
      member do
        get :respond
      end
    end
  end
  resources :scriptures
  resources :roles
  resources :selections
  resources :organizations do
    resources :groups do
    end
  end
  #root 'posts#user_posts'
  root 'journals#user_journals'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :track
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :roles
  has_many :users, through: :roles
  has_many :posts
  has_many :selections
  has_many :tracks, through: :selections
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :group
  belongs_to :user

  enum role_type: {
    teacher: 1,
    student: 2
  }

  validates :group, presence: true
  validates :user,  presence: true

end

app/models/scripture.rb
class Scripture < ApplicationRecord
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :group
  belongs_to :track
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :activities, dependent: :destroy
  accepts_nested_attributes_for :activities
  has_many :selections
  has_many :groups, through: :selections
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  has_many :roles
  has_many :groups, through: :roles
  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :posts
  has_many :journals
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    #@groups = Group.find(params[:id])
    @group = Group.find(params[:group_id])
    @posts = @group.posts.order(id: :desc)
    @tracks = @group.tracks.all  
    @user = current_user
  
    respond_to do |format|
      format.html
      format.xml { render :xml => @posts}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    group = Group.find(params[:group_id])
    @post = group.posts

    respond_to do |format|
      format.html
      format.xml { render :xml => @post }
    end
  end

  # GET /posts/new
  def new
    @group = Group.find(params[:group_id])
    @post = @group.posts.build
    @user = current_user

    respond_to do |format|
      format.html
      format.xml { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
   @group = Group.find(params[:group_id])
   @post = @group.posts.find(params[:id])
   # @post = Post.find(params[:id])
    @user = current_user
  end

  # POST /posts
  # POST /posts.json
  def create
    @group = Group.find(params[:group_id])
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id
    @groups = Group.all

    respond_to do |format|
      if @post.save
        format.html { redirect_to group_posts_path(@group), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @group = Group.find(params[:group_id])
    #@post = post.find(params[:id])
    @post = @group.posts.find(params[:id])
    @user = current_user

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to group_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    group = Group.find(params[:group_id])
    @post = group.posts.find(params[:id])
    #@post = posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to group_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_posts
    @posts = policy_scope(Post).order(id: :desc)
    @tracks = Track.all
    @user = current_user
    @groups = Group.all

  end


  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:published, :content, :user_id, :group_id, user_attributes: [:name], group_attributes: [:title])
    end

  end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def destroy
    role = Role.find(params[:id])
    role.destroy
    respond_to do |format|
      format.html { redirect_to groups_path, notice: "User was removed from the group." }
      format.json { head :no_content }
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_for([@post.group, @post]) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :published %>
    <%= f.datetime_select :published %>
  </div>-->

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :rows => "7", class: "form-control" %>
  </div>

  <!--<div class="form-group">
    <%= f.label :post_to %>
    <%= f.select :group_id, options_for_select(@user.groups.collect{ |g| [g.title, g.id] }), class: "form-control"  %>
  </div>-->
     
<p>
  <div class="actions">
    <%= f.hidden_field :group_id, value: @group.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_list.html.erb
  
  <%= render @posts %>
   

app/views/posts/_post.html.erb
<div class="card card-block" >
  <div class="card-header">
    <%= post.user.name %><br />
    <!--<%= post.group.title %> Group-->
  </div>
  <div class="card-block">
      <p class="card-text"><%= post.content %></p>
  </div>
  <div class="card-footer">
    <%=post.created_at.strftime("%B %e, %Y") %><br />
    <% if policy(post).edit? %>
    <%= link_to 'Edit', edit_group_post_path(post.group, post) %>
    <% end %>
    <% if policy(post).destroy? %> 
    <%= link_to 'Delete', group_post_path(post.group, post), method: :delete, data: { confirm: 'Are you sure?'} %>
    <% end %>
  <%#= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'} %>
  <%#= link_to 'Edit', edit_post_path(post) %>
  </div>

</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Edit Post</h1>

<%= render 'form', post: @post %>


<%= link_to 'Back', group_posts_path(@group) %>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">
            <div class="row">
              <div class="col-sm-9">
                <%= @group.title %> Group's Posts
              </div>
              <div class="col-sm-3">

            <div class="dropdown">
              <button class="btn btn-secondary btn-sm dropdown-toggle pull-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Group Members</button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <% @group.users.each do |user| %>
                <a class="dropdown-item" href="#"><%= user.name %></a>
                <% end %>
              </div>
            </div>
            </div>
            </div>
          </h4>
        </div>
      </div>
      <div class="card">
        <div class="card-block">
          <div class="container">
            <%= form_for :post, url: group_posts_path do |f| %>
              <div class="form-group">
                <%= f.label "Join the Conversation:" %>
                <%= f.text_area :content, :rows => "3", class: "form-control" %>
              </div>
              <!--<div class="form-group">
                <%= f.label :post_to %>
                <%= f.select :group_id, options_for_select(@user.groups.collect{ |g| [g.title, g.id] }), class: "form-control"  %>
              </div>-->
              <div class="actions">
                <%= f.hidden_field :group_id, value: @group.id %>
                <%= f.submit "Create Post" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= render 'list' %>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">You are on the <%= @group.title %> page.</h4>
          <p>New posts will be public.</p>
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Switch Groups</a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="<%= root_path %>">Go to Personal Journal</a>
              <% @user.groups.each do |group| %>
              <a class="dropdown-item" href="<%= group_posts_path(group) %>">Go to <%= group.title %></a>
              <% end %>
            </div>
      </div>
        </div>
      </div>
      <div class="card">
        <div class="card-block">
          <h4 class="card-title"><%= @user.name %>'s Activities</h4>
          <div class="container">
            <% if @tracks.empty? %>
              <p> There aren't any new activities.</p>
            <% end %>
            <% else @tracks.each do |track| %>
              <!--<div class="card card-block" style="max-width: 20rem;">-->
                  <h5 class="card-title"><%= track.title %></h5>
                    <!--<div class="card-block">-->
                      <% track.activities.each do |activity| %>
                        <h5><%= link_to "#{activity.title}", receive_group_track_activity_path(@group, activity.track, activity) %></h5>
                        <!--<a href="<%= receive_group_track_activity_path(@group, activity.track, activity) %>" class="list-group-item list-group-item-action"><%= activity.title %></a>-->
                      <% end %>
                      <br>
                    <!--</div>--> 
                <!--</div>-->
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>

<p>

<%= render 'form', post: @post %>

<%= link_to 'Back', group_posts_path(@group) %>
</div>

app/views/posts/show.html.erb
<div class="container">
<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/user_posts.html.erb
<div class="container-fluid">

<div class="row-fluid">
   
  <div class="col-sm-7">
      <div class="card card-block">
      <h4 class="card-title"><%= @user.name %>'s Posts</h4>
      <%#= link_to 'New Journal Post', new_user_journal_path(@user) %>
      </div>

      <!--<div class="card card-block">-->
       
        <p>
         <%= render 'list' %>
         
   
      <!-- </div> -->
  </div>

<div class="col-sm-4">
 
  <div class="card card-block">
    <h4 class="card-title">You are on your personal page.</h4>
      <p>New posts will be kept private unless marked public.</p>
        
  </div>

  <div class="card card-block">
      <h4 class="card-title">My Groups</h4>
     <div class="container-fluid">
    <% @user.groups.each do |group| %>
         <a href="<%= group_posts_path(group) %>" class="list-group-item list-group-item-action"><%= group.title %></a><br />
      <% end %>

  
 </div>     
</div>
</div>