config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :journals do
    collection do
      get '/user_journals', to: 'journals#user_journals', as: :user
    end
  end
  resources :posts
  resources :users
  resources :groups do |t|
    member do
      post :create_role
    end
    member do
      delete :delete_role
    end
    member do
      post :add_track, path: '/add_track'
    end
    member do
      delete :delete_track
    end
    resources :posts do
      collection do
        get '/user_posts', to: 'posts#user_posts', as: :user
      end
    end
    resources :tracks do
      resources :activities do
        member do
          get :receive
        end
        member do
          get :reflect
        end
        member do
          get :respond
        end
      end
    end
  end
  
  resources :tracks do |t|
  	member do
      post :create_selection
    end
    resources :activities do
      member do
        get :receive
      end
      member do
        get :reflect
      end
      member do
        get :respond
      end
    end
  end
  resources :scriptures
  resources :roles
  resources :selections
  resources :organizations do
    resources :groups do
    end
  end
  #root 'posts#user_posts'
  root 'journals#user_journals'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :track
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController 


  def index
    track = Track.find(params[:track_id])
    @activities = track.activities

    respond_to do |format|
    	format.html
    	format.xml { render :xml => @activities }
    end
  end
  
  def show
  	track = Track.find(params[:track_id])
  	@activity = track.activities.find(params[:id])

  	respond_to do |format|
  		format.html
  		format.xml { render :xml => @activity }
  	end
  end

  def new
  	track = Track.find(params[:track_id])
  	@activity = track.activities.build

  	respond_to do |format|
  		format.html
  		format.xml { render :xml => @activity }
  	end
  end

  def edit
    track = Track.find(params[:track_id])
    @activity = track.activities.find(params[:id])
  end

  def create
  	track = Track.find(params[:track_id])
  	@activity = track.activities.create(activity_params)

  	respond_to do |format|
  		if @activity.save
  			format.html { redirect_to([@activity.track, @activity], :notice => 'Activity was successfully created.') }
        #the key :location is associated to an array in order to build the correct route to the nested resource comment
            format.xml  { render :xml => @activity, :status => :created, :location => [@activity.track, @activity] }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
        end
    end
  end
  	
  def update
    track = Track.find(params[:track_id])
  	@activity = track.activities.find(params[:id])

  	respond_to do |format|
  		if @activity.update_attributes(activity_params)
  			format.html { redirect_to([@activity.track, @activity], :notice => 'Activity was successfully updated.') }
        #the key :location is associated to an array in order to build the correct route to the nested resource comment
            format.xml  { head :ok }
        else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
        end
    end
  end

  def destroy
    track = Track.find(params[:track_id])
    @activity = track.activities.find(params[:id])
    @activity.destroy
    
    respond_to do |format|
    	format.html { redirect_to(track_activities_url) }
    	format.xml { head :ok }
    end
  end

  def receive
    @activity = Activity.find(params[:id])
    track = Track.find(params[:track_id])
    @group = Group.find(params[:group_id])

  end

  def reflect
    @activity = Activity.find(params[:id])
    track = Track.find(params[:track_id])
    @group = Group.find(params[:group_id])
  end

  def respond
    @activity = Activity.find(params[:id])
    track = Track.find(params[:track_id])
    groups = Group.all
    @group = Group.find(params[:group_id])
  end
end


  private
    def activity_params
    	params.require(:activity).permit(:title, :receive, :reflect, :respond, :tracks_attributes => [:title, :description])
    end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<p>
  <strong>Activity:</strong>
  <%= activity.title %>
</p>

<p>
  <strong>Receive:</strong>
  <%= activity.receive %>
</p>

<p>
  <strong>Reflect:</strong>
  <%= activity.reflect %>
</p>

<p>
  <strong>Respond:</strong>
  <%= activity.respond %>
</p>

<p>
  <%= link_to 'Edit' %> 
  <%= link_to 'Delete', [activity.track, activity], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/activities/_form.html.erb
<%= form_for([@activity.track, @activity]) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :receive %>
    <%= f.text_area :receive, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :reflect %>
    <%= f.text_area :reflect, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :respond %>
    <%= f.text_area :respond, class: "form-control" %>
</div>
<div class="actions">
    <%= f.submit class: "btn btn-primary" %>
</div>

<% end %>

app/views/activities/edit.html.erb
<div class="container">
<h1>Edit Activity</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/:id -->
<%= link_to 'Show', [@activity.track, @activity] %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', track_activities_path(@activity.track) %>
</div>

app/views/activities/index.html.erb
<p>
<div class="container">
<div class="card card-block">
  <h1 class="card-title"><h3>Activities</h3></h1>
  <p class="card-text">

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Receive</th>
    <th>Reflect</th>
    <th>Respond</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.title %></td>
    <td><%= activity.receive %></td>
    <td><%= activity.reflect %></td>
    <td><%= activity.respond %></td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to 'Begin', receive_track_activity_path(activity.track, activity) %></td>
    <td><%= link_to 'Show', [activity.track, activity] %></td>
    <!-- /posts/:post_id/comments/:id/edit -->
    <td><%= link_to 'Edit', edit_track_activity_path(activity.track, activity)%></td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to 'Destroy',track_activity_path(activity.track, activity), method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Add a New Activity', new_track_activity_path %>  |
<%= link_to 'Back', tracks_path %><br />
 <!-- /posts/:post_id/comments/new -->
 </p>
 </div>
 </div>

app/views/activities/new.html.erb
<div class="container">
<h1>New Activity</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', track_activities_path(@activity.track)%>
</div>

app/views/activities/receive.html.erb
<div class="container">
  <div class="card">
    <div class="card-block">
      <h1 class="card-title"><%= @activity.track.title %></h1>
      <h4 class="card-title"><%= @activity.title %></h4>
        <p class="card-text">
          <div class="card">
            <div class="card-header">Receive</div>
            <div class="card-block">
              <p class="card-text" style="white-space: pre-line;" ><%= @activity.receive %></p>
            </div>
          </div>
        </p>
      <%= link_to 'Journal', root_url %>  |
      <%= link_to 'Back to Group', group_posts_path(@group) %>  |
      <%= link_to 'Next', reflect_group_track_activity_path(@group) %>
    </div> 
  </div> 
</div>

app/views/activities/reflect.html.erb
<div class="container">
  <div class="card">
    <div class="card-block">
      <h1 class="card-title"><%= @activity.track.title %></h1>
      <h4 class="card-title"><%= @activity.title %></h4>
      <p class="card-text">
        <div class="card">
          <div class="card-header">Reflect</div>
          <div class="card-block">
            <p class="card-text" style="white-space: pre-line;"><%= @activity.reflect %></p>
          </div>
        </div>
      </p>
      <%= link_to 'Back', receive_group_track_activity_path(@group) %>  |
      <%= link_to 'Journal', root_url %> |
      <%= link_to 'Back to Group', group_posts_path(@group) %>  |
      <%= link_to 'Next', respond_group_track_activity_path(@group) %>
    </div>
  </div>  
</div>

app/views/activities/respond.html.erb
<div class="container">
  <div class="card">
    <div class="card-block">
      <h1 class="card-title"><%= @activity.track.title %></h1>
      <h4 class="card-title"><%= @activity.title %></h4>
      <p class="card-text">
        <div class="card">
          <h4 class="card-header">Respond</h4>
          <div class="card-block">
            <p class="card-text" style="white-space: pre-line;"><%= @activity.respond %></p>
            <p>I want to respond with a personal post: <%= link_to 'Journal', new_journal_path %></p>
            <p>I want to respond by posting to a group: <%= link_to 'New Post', new_group_post_path(@group) %></p>
          </div>
        </div>
      </p>
      <%= link_to 'Back', reflect_group_track_activity_path(@group) %>  |
      <%= link_to 'Journal', root_url %>  |
      <%= link_to 'Back to Group', group_posts_path(@group) %>
    </div>
  </div>  
</div>

  
 

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="card card-block">
  <h1 class="card-title"></h1>
  <p class="card-text">

<p>
  <strong>Activity:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Receive:</strong>
  <%= @activity.receive %>
</p>

<p>
  <strong>Reflect:</strong>
  <%= @activity.reflect %>
</p>

<p>
  <strong>Respond:</strong>
  <%= @activity.respond %>
</p>

<p>
  <%= link_to 'Edit', edit_track_activity_path(@activity.track, @activity) %>  | 
  <%= link_to 'Back', track_activities_path(@activity.track) %>  |
  <%= link_to 'Delete', track_activity_path(@activity.track, @activity), method: :delete %>
<p>

</p>
</div>
</div>